<li> <img class="pb-fl" src="[field:image/]" alt="[field:fulltitle/]" /> 
                                    <dl class="pb-fl"> 
                                        <dt>
                                            <a href="[field:arcurl/]">[field:title/]</a>
                                        </dt> 
                                        
                                        <dd class="cnt">
                                            [field:description function='cn_substr(@me,160)'/]... 
                                        </dd> 
                                    </dl> </li>