<li> <a href="pic_detail.html?1"> <img src="[field:image/]" class="pb-block" style="width:200px;" alt="[field:fulltitle/]" /> </a> 
                                <table class="pb-opac70"> 
                                    <tbody>
                                        <tr> 
                                            <td class="tle">[field:title/]</td> 
                                            <td class="num">+[field:click/]</td> 
                                        </tr> 
                                    </tbody>
                                </table> 
                            </li>