<li> <a href="[field:arcurl/]"><img src="[field:image/]" class="pb-fl" alt="[field:title/]" /></a> 
        <dl> 
         <dt>
          <a href="[field:arcurl/]">[field:title/]</a>
         </dt> 
         <dd class="pb-mt10">
          <strong>日期</strong> ： 
          <a>[field:pubdate function="GetDateMK(@me)"/]</a>
         </dd>  
         <dd>
          [field:description/]
         </dd> 
        </dl> 
        </li>