<?php
$z[0]=Array("arclist","\n            <li> \n            <span>.</span> <a href=\"[field:arcurl/]\">[field:title/]</a> \n            <div class=\"pb-line2\"></div> \n            </li>\n            ",368,586);
$z[0][4]['row']="10";
$z[0][4]['orderby']="click";
$z[1]=Array("arclist","\n            <div style=\"left:150px;height:150px;top:15px;\" class=\"single\"> \n             <a title=\"[field:fulltitle/]\" href=\"[field:arcurl/]\"><img alt=\"[field:fulltitle/]\" src=\"[field:litpic/]\" style=\"width:145px;\" /></a> \n            </div>\n            ",895,1233);
$z[1][4]['limit']="0,1";
$z[1][4]['typeid']="2";
$z[1][4]['orderby']="pubdate";
$z[1][4]['type']="image";
$z[2]=Array("arclist","\n            <div style=\"left:0px;height:150px;top:15px;\" class=\"single\"> \n             <a title=\"[field:fulltitle/]\" href=\"[field:arcurl/]\"><img alt=\"[field:fulltitle/]\" src=\"[field:litpic/]\" style=\"width:145px;\" /></a>  \n            </div>\n            ",1259,1596);
$z[2][4]['limit']="1,1";
$z[2][4]['typeid']="2";
$z[2][4]['orderby']="pubdate";
$z[2][4]['type']="image";
$z[3]=Array("arclist","\n            <div style=\"left:150px;height:150px;top:170px;\" class=\"single\"> \n             <a title=\"[field:fulltitle/]\" href=\"[field:arcurl/]\"><img alt=\"[field:fulltitle/]\" src=\"[field:litpic/]\" style=\"width:145px;\" /></a> \n            </div>\n            ",1622,1961);
$z[3][4]['limit']="2,1";
$z[3][4]['typeid']="2";
$z[3][4]['orderby']="pubdate";
$z[3][4]['type']="image";
$z[4]=Array("arclist","\n            <div style=\"left:0px;height:150px;top:170px;\" class=\"single\"> \n             <a title=\"[field:fulltitle/]\" href=\"[field:arcurl/]\"><img alt=\"[field:fulltitle/]\" src=\"[field:litpic/]\" style=\"width:145px;\" /></a>\n            </div>\n            ",1987,2323);
$z[4][4]['limit']="3,1";
$z[4][4]['typeid']="2";
$z[4][4]['orderby']="pubdate";
$z[4][4]['type']="image";
$z[5]=Array("arclist","\n            <div style=\"left:150px;height:150px;top:325px;\" class=\"single\"> \n             <a title=\"[field:fulltitle/]\" href=\"[field:arcurl/]\"><img alt=\"[field:fulltitle/]\" src=\"[field:litpic/]\" style=\"width:145px;\" /></a>\n            </div>\n            ",2349,2687);
$z[5][4]['limit']="4,1";
$z[5][4]['typeid']="2";
$z[5][4]['orderby']="pubdate";
$z[5][4]['type']="image";
$z[6]=Array("arclist","\n            <div style=\"left:0px;height:150px;top:325px;\" class=\"single\"> \n             <a title=\"[field:fulltitle/]\" href=\"[field:arcurl/]\"><img alt=\"[field:fulltitle/]\" src=\"[field:litpic/]\" style=\"width:145px;\" /></a> \n            </div> \n            ",2713,3051);
$z[6][4]['limit']="5,1";
$z[6][4]['typeid']="2";
$z[6][4]['orderby']="pubdate";
$z[6][4]['type']="image";

?>